# Site settings
title: Probability
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A course in Probability at Reed College.
baseurl: /math-391
url: http://andrewpbray.github.io
#twitter_username: jekyllrb
#github_username:  jekyll
urllabel: "Andrew's Webpage"

# Build settings
markdown: kramdown
